### ISSUE TITLE
Korea local name system changed to road-name

### ISSUE THREAD

**Issue by YunYeongChang** [implude/local-community-backend#1]
should change db schema and code

**Comment by YunYeongChang** [comment]
@Malang2 어떻게 했으면 좋겠어요?
@ksh1743 지금 어디까지 구현되었는지 알려주세요

**Comment by Malang2** [comment]
지금 우리나라에서 쓰는 도로명 주소가 제일 좋긴 합니다
우선 성호 진도 보고 결정하는 게 나을 듯 합니다

**Comment by Malang2** [comment]
@ksh1743 과제기간 끝나고 답변주세요

**Comment by YunYeongChang** [comment]
@ksh1743  답변 주라고요

**Comment by YunYeongChang** [comment]
GoogleAPI를 통해 중소정보를 얻고,
Json object로 디비에 저장가능
JwtToken으로 디비에 저장가능
암호화 여부 선택해야함

**Comment by YunYeongChang** [comment]
backend changed to save areaString using google-place-picker api
[https://github.com/implude/local-community-backend/commit/0f383768e608fd078c7e90702b375205a940fe83](url)

**Comment by YunYeongChang** [comment]
we need to change area-system to use 한국도로명주소센터 api.
